import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traducciones completas
const translations = {
  es: {
    // Header y navegación
    'nav.agora': '🏛️ Ágora',
    'nav.boulevard': '🛍️ Boulevard',
    'nav.dashboard': '📊 Dashboard',
    'nav.home': '🏠 Inicio',
    'nav.install': '📱 Instalar App',
    'nav.login': 'Iniciar Sesión',
    'nav.help': 'Ayuda',
    
    // Hero Section
    'hero.title': 'HUMANBIBLIO',
    'hero.subtitle1': 'Libera tu comunicación',
    'hero.subtitle2': 'Conecta conscientemente',
    'hero.subtitle3': 'Crece orgánicamente',
    'hero.subtitle4': 'Vive auténticamente',
    'hero.description': 'Libera tu comunicación de algoritmos manipulativos. Conecta auténticamente con personas y negocios.',
    'hero.description2': 'Comunicación libre y orgánica.',
    'hero.cta.agora': '🏛️ Entrar al Ágora',
    'hero.cta.boulevard': '🛍️ Explorar Boulevard',
    'hero.scroll': 'Descubre más abajo',
    'hero.stat.ai': 'Personalidades IA',
    'hero.stat.manipulation': 'Sin Manipulación',
    'hero.stat.connections': 'Conexiones Auténticas',
    'hero.stat.app': 'App Nativa',
    
    // Ágora
    'agora.title': '🏛️ Ágora - El Encuentro de Mentes Brillantes',
    'agora.description': 'Liberamos la comunicación humana de la manipulación algorítmica. Aquí, TÚ decides con quién conectar, cuándo y cómo.',
    'agora.join': '🏛️ Únete al Ágora',
    'agora.join.subtitle': 'Crea tu perfil con 3 temas únicos + info dating discreta',
    'agora.manifesto.title': 'La Inteligencia Natural',
    'agora.manifesto.subtitle': 'Liberamos la comunicación humana de la manipulación algorítmica',
    'agora.manifesto.description': 'Aquí, TÚ decides con quién conectar, cuándo y cómo.',
    'agora.profiles.tab': '👥 Perfiles',
    'agora.universe.tab': '🌌 No Estamos Solos',
    'agora.search.placeholder': 'Buscar personas, profesiones, habilidades, intereses...',
    'agora.wb.title': '¿Vendes productos o servicios?',
    'agora.wb.description': 'Compra tu espacio comercial en World Boulevard',
    'agora.wb.button': '🛍️ Comprar Espacio WB',
    'agora.wb.select.user': '¿Para qué usuario quieres comprar el espacio comercial?',
    'agora.wb.plan.basic': 'Plan Básico',
    'agora.wb.plan.premium': 'Plan Premium',
    'agora.wb.plan.enterprise': 'Plan Enterprise',
    'agora.wb.benefits.title': '🎯 Beneficios World Boulevard:',
    'agora.wb.benefits.profile': '🛍️ Perfil comercial profesional',
    'agora.wb.benefits.gallery': '📸 Galería multimedia expandible',
    'agora.wb.benefits.chat': '💬 Chat directo con clientes',
    'agora.wb.benefits.geo': '🌍 Geolocalización inteligente',
    'agora.wb.benefits.analytics': '📊 Analytics de interacciones',
    'agora.wb.benefits.carousel': '🎠 Carrusel publicitario',
    'agora.mindmate.title': '¡Encuentra tu mente gemela!',
    'agora.mindmate.description': 'Conexiones intelectuales profundas y conscientes',
    'agora.mindmate.button': '🧠 Encontrar Mente Gemela',
    'agora.universe.title': 'No estás solo en el Universo',
    'agora.universe.description': 'Alguien quiere hablar contigo',
    'agora.universe.button': '🌍 Conectar con Humanos Reales',
    
    // World Boulevard
    'boulevard.title': '🛍️ World Boulevard - Comercio Orgánico',
    'boulevard.description': 'Descubre negocios únicos y auténticos. Conecta directamente con emprendedores excepcionales.',
    'boulevard.register': '🛍️ Registrar mi Negocio',
    'boulevard.register.subtitle': 'Crea tu espacio comercial en World Boulevard',
    'boulevard.featured.title': '⭐ Negocios Destacados',
    'boulevard.featured.description': 'Descubre los negocios más auténticos y únicos de World Boulevard',
    'boulevard.sponsors.title': '🏆 Financiadores y Socios Destacados',
    'boulevard.sponsors.description': 'Conoce a los visionarios que impulsan la innovación en HUMANBIBLIO',
    'boulevard.tabs.businesses': '🛍️ Negocios Destacados',
    'boulevard.tabs.sponsors': '🏆 Financiadores y Socios',
    'boulevard.search.placeholder': 'Buscar negocios, categorías, productos, servicios...',
    'boulevard.contact.now': '💬 Contactar Ahora',
    'boulevard.call': '📞 Llamar',
    'boulevard.website': '🌐 Web',
    'boulevard.location': '📍 Ubicación',
    'boulevard.badge.featured': '⭐ Destacado',
    'boulevard.organic.certified': 'Comercio Orgánico Certificado',
    'boulevard.organic.growth': 'Crecimiento auténtico',
    'boulevard.organic.no_ads': 'Sin publicidad forzada',
    'boulevard.organic.verified': 'Verificado por HUMANBIBLIO',
    'boulevard.organic.direct': 'Comunicación directa',
    'boulevard.info.organic': 'Comercio Orgánico',
    'boulevard.info.direct': 'Conexión Directa',
    'boulevard.info.no_intermediaries': 'Sin Intermediarios',
    'boulevard.autoplay.pause': 'Pausar auto-reproducción',
    'boulevard.autoplay.play': 'Activar auto-reproducción',
    'boulevard.sponsor.promotion.title': '💡 ¿Quieres aparecer aquí?',
    'boulevard.sponsor.promotion.description': 'Financia proyectos innovadores en "No estás solo en el Universo" y obtén reconocimiento premium en World Boulevard',
    'boulevard.sponsor.promotion.button': '🌌 Explorar Proyectos para Financiar',
    'boulevard.sponsor.empty.title': 'Sé el Primer Financiador Destacado',
    'boulevard.sponsor.empty.description': 'Financia proyectos innovadores y aparece en este carrusel premium',
    'boulevard.sponsor.empty.button': '🌟 Convertirme en Financiador',
    'boulevard.sponsor.empty.alert': '🚀 Ve a "No estás solo en el Universo" para financiar proyectos y aparecer aquí',
    'boulevard.sponsor.level.platinum': 'Financiador Platino',
    'boulevard.sponsor.level.gold': 'Financiador Oro',
    'boulevard.sponsor.level.silver': 'Financiador Plata',
    'boulevard.sponsor.level.bronze': 'Financiador Bronce',
    'boulevard.sponsor.funded': 'financiados',
    'boulevard.sponsor.active.message': 'es un financiador activo que apoya proyectos innovadores en HUMANBIBLIO.',
    'boulevard.sponsor.impact.title': 'Impacto como financiador:',
    'boulevard.sponsor.impact.projects': 'proyectos financiados',
    'boulevard.sponsor.impact.entrepreneurs': 'emprendedores apoyados',
    'boulevard.sponsor.impact.total': 'impacto total',
    'boulevard.sponsor.button.business': '🛍️ Ver Negocio en Boulevard',
    'boulevard.sponsor.button.profile': '👤 Ver Perfil en Ágora',
    'boulevard.sponsor.button.contact': '💬 Contactar',
    'boulevard.sponsor.button.collaborate': '🤝 Colaborar',
    'boulevard.sponsor.alert.contact': '💬 Iniciando conversación con',
    'boulevard.sponsor.alert.collaborate': '🤝 Explorando colaboraciones con',
    'boulevard.sponsor.info.featured': 'Financiadores Destacados',
    'boulevard.sponsor.info.investment': 'Inversión Inteligente',
    'boulevard.sponsor.info.recognition': 'Reconocimiento Premium',
    'funder.total.funded': 'Total financiado',
    'funder.count.singular': 'financiador',
    'funder.count.plural': 'financiadores',
    'funder.project.success': 'Proyecto financiado exitosamente',
    'funder.funded.by': '🏆 Financiado por',

    // Expanded Business Profile
    'expanded.business.tab.info': 'Información',
    'expanded.business.tab.reviews': 'Reseñas',
    'expanded.business.reviews.count': 'reseñas',
    'expanded.business.services.title': 'Servicios y Productos',

    // Business Card
    'business.card.services': 'Servicios',
    'business.card.view': 'Ver Perfil',

    // User Card
    'user.card.interests': 'Intereses',
    'user.card.view': 'Ver Perfil',

    // Project Card
    'project.card.category': 'Categoría',
    'project.card.funding': 'Financiación',
    'project.card.likes': 'Likes',
    'project.card.comments': 'Comentarios',

    // Dashboard
    'dashboard.title': '📊 Dashboard Personal',
    'dashboard.welcome': 'Bienvenido',
    'dashboard.overview': '📊 Resumen',
    'dashboard.nearby': '🌍 Cerca de Mí',
    'dashboard.matching': '🎯 Matching IA',
    'dashboard.connections': 'Conexiones',
    'dashboard.messages': 'Mensajes',
    'dashboard.rating': 'Valoración',
    'dashboard.recent.activity': 'Actividad Reciente',
    'dashboard.new.connection': 'Nueva conexión con',
    'dashboard.message.from': 'Mensaje de',
    'dashboard.hours.ago': 'Hace {hours} horas',
    'dashboard.nearby.title': '🌍 Cerca de Mí',
    'dashboard.nearby.found': 'elementos encontrados en',
    'dashboard.nearby.radius': 'Radio:',
    'dashboard.nearby.map': '🗺️ Mapa',
    'dashboard.nearby.list': '📋 Lista',
    'dashboard.matching.title': '🎯 Matching con IA',
    'dashboard.matching.description': 'Nuestro algoritmo de IA ha analizado tu perfil y encontrado las mejores conexiones para ti',
    'dashboard.matching.average': 'Compatibilidad Promedio',
    'dashboard.matching.based': 'Basado en {count} perfiles analizados',
    
    // Impact Metrics
    'impact.title': '📊 Impacto Real en Números',
    'impact.subtitle': 'Métricas del Piloto: Conexiones auténticas, no tiempo perdido.',
    'impact.connections.label': 'Usuarios Piloto',
    'impact.connections.desc': 'Personas probando la plataforma',
    'impact.messages.label': 'Conversaciones',
    'impact.messages.desc': 'Intercambios genuinos durante el piloto',
    'impact.businesses.label': 'Negocios Registrados',
    'impact.businesses.desc': 'Comercios en World Boulevard',
    'impact.satisfaction.label': 'Satisfacción',
    'impact.satisfaction.desc': 'Feedback positivo de usuarios piloto',

    // Features
    'features.title': '🌟 Funcionalidades Revolucionarias',
    'features.description': 'Cada funcionalidad está diseñada para liberar tu potencial humano, no para capturar tu atención.',
    'features.amplifies': 'Tecnología que amplifica tu humanidad',
    'features.ai.title': 'IA Contextual',
    'features.ai.description': 'Conversaciones inteligentes que se adaptan al expertise de cada persona',
    'features.ai.detail1': '4 personalidades especializadas',
    'features.ai.detail2': 'Respuestas según profesión',
    'features.ai.detail3': 'Análisis de sentimiento',
    'features.ai.detail4': 'Memoria conversacional',
    'features.connections.title': 'Conexiones Conscientes',
    'features.connections.description': 'Cada conexión es intencional, sin algoritmos manipulativos',
    'features.connections.detail1': 'Flujo de intención',
    'features.connections.detail2': 'Calidad sobre cantidad',
    'features.connections.detail3': 'Sin adicción diseñada',
    'features.connections.detail4': 'Comunicación auténtica',
    'features.matching.title': 'Matching Inteligente',
    'features.matching.description': 'Algoritmos que conectan por compatibilidad real, no engagement',
    'features.matching.detail1': 'Análisis de intereses',
    'features.matching.detail2': 'Compatibilidad profesional',
    'features.matching.detail3': 'Proximidad geográfica',
    'features.matching.detail4': 'Objetivos comunes',
    'features.pwa.title': 'Experiencia Nativa',
    'features.pwa.description': 'PWA instalable que funciona como app nativa',
    'features.pwa.detail1': 'Instalación directa',
    'features.pwa.detail2': 'Funciona offline',
    'features.pwa.detail3': 'Notificaciones push',
    'features.pwa.detail4': 'Acceso rápido',
    'features.geo.title': 'Geolocalización Inteligente',
    'features.geo.description': 'Descubre personas y negocios increíbles cerca de ti',
    'features.geo.detail1': 'Mapa interactivo',
    'features.geo.detail2': 'Filtros de distancia',
    'features.geo.detail3': 'Privacidad protegida',
    'features.geo.detail4': 'Búsqueda local',
    'features.commerce.title': 'Comercio Orgánico',
    'features.commerce.description': 'Negocios que crecen auténticamente, sin publicidad forzada',
    'features.commerce.detail1': 'Crecimiento natural',
    'features.commerce.detail2': 'Sin intermediarios',
    'features.commerce.detail3': 'Relaciones directas',
    'features.commerce.detail4': 'Comercio consciente',
    
    // Comparison
    'comparison.title': '⚔️ HUMANBIBLIO vs Redes Tradicionales',
    'comparison.subtitle': 'La diferencia es revolucionaria',
    'comparison.traditional': 'Redes Tradicionales',
    'comparison.humanbiblio': 'HUMANBIBLIO',
    
    // Traditional Networks
    'traditional.addiction.title': 'Diseñadas para Adicción',
    'traditional.addiction.desc': 'Economía de la atención - tu tiempo es su producto',
    'traditional.addiction.1': 'Scroll infinito sin fin',
    'traditional.addiction.2': 'Notificaciones constantes',
    'traditional.addiction.3': 'FOMO (Fear of Missing Out)',
    
    'traditional.algorithms.title': 'Algoritmos Manipulativos',
    'traditional.algorithms.desc': 'Deciden qué ves y cuándo lo ves',
    'traditional.algorithms.1': 'Filtros de contenido opacos',
    'traditional.algorithms.2': 'Priorización por engagement',
    'traditional.algorithms.3': 'Sesgo hacia controversia',
    
    'traditional.ads.title': 'Publicidad Intrusiva',
    'traditional.ads.desc': 'Interrumpe conexiones auténticas',
    'traditional.ads.1': 'Anuncios entre contenido',
    'traditional.ads.2': 'Targeting invasivo',
    'traditional.ads.3': 'Comercialización de datos',
    
    'traditional.engagement.title': 'Engagement Artificial',
    'traditional.engagement.desc': 'Métricas vacías sin significado real',
    'traditional.engagement.1': 'Likes como validación',
    'traditional.engagement.2': 'Competencia por atención',
    'traditional.engagement.3': 'Superficialidad incentivada',
    
    'traditional.data.title': 'Datos como Producto',
    'traditional.data.desc': 'Tu privacidad se monetiza',
    'traditional.data.1': 'Perfilado sin consentimiento',
    'traditional.data.2': 'Venta a terceros',
    'traditional.data.3': 'Falta de transparencia',
    
    'traditional.result': 'Resultado: Malestar + Adicción',
    'traditional.result.desc': 'Comunicación subvertida por intereses comerciales',
    
    // HUMANBIBLIO
    'humanbiblio.authentic.title': 'Comunicación auténtica',
    'humanbiblio.authentic.desc': 'Emisor → Receptor directo',
    'humanbiblio.authentic.1': 'Flujo de intención clara',
    'humanbiblio.authentic.2': 'Conexiones significativas',
    'humanbiblio.authentic.3': 'Sin adicción diseñada',
    
    'humanbiblio.ai.title': 'IA como Herramienta',
    'humanbiblio.ai.desc': 'Tú mantienes el control total',
    'humanbiblio.ai.1': 'IA contextual especializada',
    'humanbiblio.ai.2': 'Respuestas según expertise',
    'humanbiblio.ai.3': 'Transparencia completa',
    
    'humanbiblio.commerce.title': 'Comercio Orgánico',
    'humanbiblio.commerce.desc': 'Crecimiento auténtico sin publicidad forzada',
    'humanbiblio.commerce.1': 'Sin intermediarios',
    'humanbiblio.commerce.2': 'Conexión directa',
    'humanbiblio.commerce.3': 'Crecimiento natural',
    
    'humanbiblio.authentic2.title': 'Autenticidad Real',
    'humanbiblio.authentic2.desc': 'Conexiones genuinas y significativas',
    'humanbiblio.authentic2.1': 'Perfiles reales verificados',
    'humanbiblio.authentic2.2': 'Conversaciones profundas',
    'humanbiblio.authentic2.3': 'Relaciones duraderas',
    
    'humanbiblio.privacy.title': 'Privacidad Respetada',
    'humanbiblio.privacy.desc': 'Tus datos son tuyos y solo tuyos',
    'humanbiblio.privacy.1': 'Control total de datos',
    'humanbiblio.privacy.2': 'Sin venta a terceros',
    'humanbiblio.privacy.3': 'Transparencia absoluta',
    
    'humanbiblio.result': 'Resultado: Bienestar + Crecimiento',
    'humanbiblio.result.desc': 'Comunicación auténtica que amplifica tu humanidad',
    
    // Natural Intelligence Manifesto
    'manifesto.title': 'La Inteligencia Natural',
    'manifesto.subtitle': 'Liberamos la comunicación humana de la manipulación algorítmica',
    'manifesto.description': 'Aquí, TÚ decides con quién conectar, cuándo y cómo.',
    'manifesto.problem.title': 'Redes Tradicionales',
    'manifesto.solution.title': 'HUMANBIBLIO',
    'manifesto.mission.title': 'Nuestra Misión',
    'manifesto.mission.description': 'En HUMANBIBLIO, TÚ controlas tu comunicación, no los algoritmos. Cada conexión es intencional, cada conversación es auténtica, y cada negocio crece de forma libre y orgánica.',
    'manifesto.channel.problem': 'El canal es el emisor: "¡No te desconectes, atiéndeme!"',
    'manifesto.attention.economy': 'Economía de la atención: Tu tiempo = su producto',
    'manifesto.intrusive.ads': 'Publicidad intrusiva: Interrumpe conexiones reales',
    'manifesto.cognitive.dissonance': 'Disonancia cognitiva: Malestar + adicción',
    'manifesto.subverted.communication': 'Comunicación subvertida: Algoritmos deciden por ti',
    'manifesto.authentic.communication': 'Comunicación auténtica: Emisor → Receptor directo',
    'manifesto.natural.intelligence': 'Inteligencia Natural: Tu criterio + IA como herramienta',
    'manifesto.organic.commerce': 'Comercio orgánico: Sin publicidad forzada',
    'manifesto.conscious.connections': 'Conexiones conscientes: Calidad sobre cantidad',
    'manifesto.creative.freedom': 'Libertad creativa: Expansión auténtica',
    
    // Universe Section
    'universe.title': 'No Estás Solo en el Universo (YANA)',
    'universe.subtitle': 'Mientras buscamos vida extraterrestre, millones de humanos viven en soledad. Alguien en este momento quiere hablar contigo.',
    'universe.paradox.title': 'La Paradoja Humana',
    'universe.paradox.description': 'Gastamos billones buscando señales del espacio exterior, pero ignoramos las señales de soledad de millones de personas extraordinarias que están a un click de distancia. HUMANBIBLIO resuelve esta paradoja.',
    'universe.tabs.explore': 'Explorar Universo',
    'universe.tabs.together': 'Hagámoslo Juntos',
    'universe.tabs.news': 'Actualidades',
    'universe.explore.title': 'Explorar Universo',
    'universe.together.title': 'Hagámoslo Juntos',
    'universe.news.title': 'Actualidades del Universo',
    'universe.news.subtitle': 'Los proyectos e ideas que más conversaciones están generando en la comunidad',
    'universe.publish.project': 'Publicar Mi Proyecto',
    'universe.most.popular': 'Proyecto Más Popular',
    'universe.most.popular.subtitle': 'El proyecto que más conversaciones está generando',
    'universe.trending.projects': 'Proyectos en Tendencia',
    'universe.community.impact': 'Impacto de la Comunidad',
    'universe.active.projects': 'Proyectos Activos',
    'universe.total.likes': 'Likes Totales',
    'universe.connections': 'Conexiones',
    'universe.seeking.partners': 'Buscando Socios',
    
    // Project Actions
    'project.like': 'Me Interesa',
    'project.contact': 'Contactar',
    'project.funded.by': 'Financiado por',
    'project.looking.funding': 'Busca Financiación',
    'project.looking.partners': 'Busca Socios',
    'project.looking.collaboration': 'Busca Colaboradores',
    'project.looking.discussion': 'Busca Conversación',
    'project.published': 'Publicado',
    'project.likes': 'likes',
    'project.contacts': 'contactos',
    'project.conversations': 'conversaciones',
    
    // Call to Action Section
    'cta.title': '🌟 Únete a la Revolución',
    'cta.subtitle': 'Sé parte del cambio hacia una comunicación digital más humana y auténtica',
    'cta.agora.title': 'El Ágora',
    'cta.agora.desc': 'Conecta con mentes brillantes. Descubre profesionales extraordinarios con IA contextual.',
    'cta.agora.feature1': 'Chat IA especializado',
    'cta.agora.feature2': 'Matching inteligente',
    'cta.agora.feature3': 'Comunicación multimedia',
    'cta.agora.button': '🏛️ Entrar al Ágora',
    'cta.boulevard.title': 'World Boulevard',
    'cta.boulevard.desc': 'Descubre negocios únicos. Comercio orgánico sin publicidad manipulativa.',
    'cta.boulevard.feature1': 'Comercio orgánico',
    'cta.boulevard.feature2': 'Galería multimedia',
    'cta.boulevard.feature3': 'Conexión directa',
    'cta.boulevard.button': '🛍️ Explorar Boulevard',
    'cta.dashboard.title': 'Dashboard',
    'cta.dashboard.desc': 'Tu centro de control personal. Estadísticas, geolocalización y matching IA.',
    'cta.dashboard.feature1': 'Analytics personales',
    'cta.dashboard.feature2': 'Explorador "Cerca de mí"',
    'cta.dashboard.feature3': 'Matching con IA',
    'cta.dashboard.button': '📊 Abrir Dashboard',
    'cta.future.title': 'El Futuro de la Comunicación Digital',
    'cta.future.desc': 'HUMANBIBLIO no es solo una plataforma, es un movimiento hacia la Inteligencia Natural - donde la tecnología amplifica nuestra humanidad en lugar de reemplazarla.',

    // Action Buttons
    'action.wb.title': '¿Vendes productos o servicios?',
    'action.wb.desc': 'Compra tu espacio comercial en World Boulevard',
    'action.wb.button': '🛍️ Comprar Espacio WB',
    
    'action.soulmate.title': '¡Encuentra tu mente gemela!',
    'action.soulmate.desc': 'Conexiones intelectuales profundas y conscientes',
    'action.soulmate.button': '🧠 Encontrar Mente Gemela',
    
    'action.universe.title': 'No estás solo en el Universo',
    'action.universe.desc': 'Alguien quiere hablar contigo',
    'action.universe.button': '🌍 Conectar con Humanos Reales',
    
    // Forms and Modals
    'form.name': 'Nombre completo',
    'form.email': 'Email',
    'form.password': 'Contraseña',
    'form.profession': 'Profesión',
    'form.bio': 'Biografía',
    'form.location': 'Ubicación',
    'form.interests': 'Intereses',
    'form.cancel': 'Cancelar',
    'form.submit': 'Enviar',
    'form.save': 'Guardar',
    'form.close': 'Cerrar',
    'form.required': 'Requerido',
    'form.optional': 'Opcional',
    
    // Business Forms
    'business.form.title': 'Registrar mi Negocio',
    'business.form.subtitle': 'Crea tu espacio comercial en World Boulevard',
    'business.form.name': 'Nombre del Negocio',
    'business.form.category': 'Categoría',
    'business.form.description': 'Descripción del Negocio',
    'business.form.products': 'Productos y Servicios',
    'business.form.contact.email': 'Email de Contacto',
    'business.form.contact.phone': 'Teléfono',
    'business.form.website': 'Sitio Web',
    'business.form.target': '¿A quién está dirigido tu negocio?',
    'business.form.experience': 'Años de Experiencia',
    'business.form.goals': '¿Qué esperas lograr en World Boulevard?',
    'business.form.includes.title': 'Tu espacio en World Boulevard incluye:',
    'business.form.includes.profile': 'Perfil comercial destacado',
    'business.form.includes.gallery': 'Galería multimedia expandible',
    'business.form.includes.chat': 'Chat directo con clientes',
    'business.form.includes.geo': 'Geolocalización inteligente',
    'business.form.includes.analytics': 'Analytics de interacciones',
    'business.form.includes.certification': 'Certificación "Comercio Orgánico"',
    'business.form.philosophy.title': 'Filosofía World Boulevard',
    'business.form.philosophy.description': 'En World Boulevard creemos en el crecimiento orgánico y auténtico. Tu negocio crecerá por la calidad de tus productos/servicios y la autenticidad de tus conexiones, no por algoritmos manipulativos.',
    
    // User Cards
    'user.card.message': 'Enviar mensaje',
    'user.card.call': 'Llamar',
    'user.card.video': 'Videollamada',
    'user.card.voice': 'Mensaje de voz',
    'user.card.wb.sells': 'Vende',
    'user.card.wb.view': 'Ver perfil comercial de {name} en World Boulevard',
    'user.card.languages': 'Idiomas',
    'user.card.from': 'De',

    // Business Cards
    'business.card.contact': 'Contactar',
    'business.card.call': 'Llamar',
    'business.card.website': 'Sitio Web',
    'business.card.location': 'Ubicación',
    'business.card.rating': 'Valoración promedio',
    'business.card.reviews': 'reseñas',

    // Communication
    'communication.hub.title': '¿Cómo quieres comunicarte?',
    'communication.chat.title': 'Chat Inteligente',
    'communication.chat.description': 'IA contextual especializada',
    'communication.voice.title': 'Llamada de Voz',
    'communication.voice.description': 'Conversación en tiempo real',
    'communication.video.title': 'Videollamada',
    'communication.video.description': 'Conexión visual completa',
    'communication.audio.title': 'Mensaje de Voz',
    'communication.audio.description': 'Grabación de audio personal',
    'communication.natural.intelligence': 'Inteligencia Natural',
    'communication.natural.description': 'Cada conversación es auténtica, sin algoritmos manipulativos. La IA responde según la expertise real de la persona.',
    
    // Search and Filters
    'search.loading': 'Buscando...',
    'search.results': 'resultados para',
    'search.no.results': 'No se encontraron resultados',
    'search.suggestions': 'Sugerencias',
    'search.recent': 'Búsquedas recientes',
    'search.filters': 'Filtros avanzados',
    'search.clear': 'Limpiar búsqueda',
    'search.apply': 'Aplicar filtros',
    'search.all.locations': 'Todas las ubicaciones',
    'search.add.interest': 'Agregar interés',
    
    // Geolocation
    'geo.title': 'Descubre lo que está cerca',
    'geo.description': 'Activa la geolocalización para encontrar personas y negocios increíbles cerca de ti',
    'geo.activate': '🌍 Activar Geolocalización',
    'geo.permission.title': 'Descubre lo que está cerca',
    'geo.permission.description': 'HUMANBIBLIO puede mostrarte personas y negocios cercanos a tu ubicación. Tu privacidad está protegida.',
    'geo.privacy.title': 'Tu privacidad es importante',
    'geo.privacy.local': 'Solo para mostrar resultados cercanos',
    'geo.privacy.no.store': 'No almacenamos tu ubicación',
    'geo.privacy.disable': 'Puedes desactivarlo cuando quieras',
    'geo.privacy.no.share': 'No compartimos datos con terceros',
    'geo.discover.title': 'Qué puedes descubrir',
    'geo.discover.professionals': 'Profesionales y expertos en tu área',
    'geo.discover.businesses': 'Negocios locales únicos y auténticos',
    'geo.discover.events': 'Eventos y oportunidades cercanas',
    'geo.discover.connections': 'Conexiones significativas en tu ciudad',
    
    // PWA
    'pwa.install.title': '¡Instala HUMANBIBLIO!',
    'pwa.install.description': 'Obtén la experiencia completa instalando nuestra PWA. Funciona como una aplicación nativa:',
    'pwa.install.faster': 'Acceso más rápido desde tu pantalla de inicio',
    'pwa.install.offline': 'Funciona sin conexión a internet',
    'pwa.install.notifications': 'Notificaciones push (próximamente)',
    'pwa.install.native': 'Experiencia como app nativa',
    'pwa.install.button': '📱 Instalar App',
    'pwa.install.later': 'Ahora no',
    'pwa.install.tip': 'Si cierras esta ventana, puedes volver a abrirla con el botón "📱 Instalar App" en el header.',

    // Auth Modal
    'auth.login.title': '🔑 Iniciar Sesión',
    'auth.signup.title': '📝 Crear Cuenta',
    'auth.login.subtitle': 'Accede a tu cuenta',
    'auth.signup.subtitle': 'Únete a HUMANBIBLIO',
    'auth.fullname': 'Nombre completo',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.login.button': 'Iniciar Sesión',
    'auth.signup.button': 'Crear Cuenta',
    'auth.processing': 'Procesando...',
    'auth.no.account': '¿No tienes cuenta? Regístrate',
    'auth.have.account': '¿Ya tienes cuenta? Inicia sesión',
    'auth.looking.for': '¿Buscas algo específico?',
    'auth.join.agora': '🏛️ Únete al Ágora (Personas)',
    'auth.register.business': '🛍️ Registrar Negocio (World Boulevard)',
    'auth.required': 'Debes iniciar sesión para crear un negocio',

    // Agora Registration Form
    'agora.form.title': '🏛️ Únete al Ágora',
    'agora.form.subtitle': 'El Encuentro de Mentes Extraordinarias',
    'agora.form.step': 'Paso',
    'agora.form.of': 'de',
    'agora.form.completed': 'completado',
    'agora.form.previous': '← Anterior',
    'agora.form.next': 'Siguiente →',
    'agora.form.join': '🏛️ Unirse al Ágora',
    'agora.form.creating': 'Creando cuenta...',
    'agora.form.step1.title': 'Información Básica',
    'agora.form.step1.subtitle': 'Comencemos con tus datos fundamentales',
    'agora.form.step2.title': 'Tus 3 Temas de Intercambio',
    'agora.form.step2.subtitle': 'Escribe libremente los 3 temas sobre los que te encanta conversar',
    'agora.form.step3.title': 'Finalizar Perfil',
    'agora.form.step3.subtitle': 'Información adicional y objetivos de conexión',
    'agora.form.fullname': 'Nombre Completo *',
    'agora.form.fullname.placeholder': 'Tu nombre completo',
    'agora.form.email': 'Email *',
    'agora.form.email.placeholder': 'tu@email.com',
    'agora.form.password': 'Contraseña *',
    'agora.form.password.placeholder': 'Mínimo 6 caracteres',
    'agora.form.confirm.password': 'Confirmar Contraseña *',
    'agora.form.confirm.password.placeholder': 'Repite tu contraseña',
    'agora.form.dating.title': 'Información Personal (Opcional y Discreta)',
    'agora.form.age': 'Edad (Opcional)',
    'agora.form.age.not.say': 'Prefiero no decir',
    'agora.form.age.18.25': '18-25 años',
    'agora.form.age.26.35': '26-35 años',
    'agora.form.age.36.45': '36-45 años',
    'agora.form.age.46.55': '46-55 años',
    'agora.form.age.56plus': '56+ años',
    'agora.form.relationship': 'Estado Civil (Opcional)',
    'agora.form.relationship.not.say': 'Prefiero no decir',
    'agora.form.relationship.single': 'Soltero/a',
    'agora.form.relationship.dating': 'En relación',
    'agora.form.relationship.married': 'Casado/a',
    'agora.form.relationship.divorced': 'Divorciado/a',
    'agora.form.relationship.widowed': 'Viudo/a',
    'agora.form.relationship.complicated': 'Es complicado',
    'agora.form.looking.for': '¿Qué buscas en HUMANBIBLIO? (Opcional - Selecciona todos los que apliquen)',
    'agora.form.privacy.level': 'Nivel de Privacidad',
    'agora.form.privacy.public': 'Público',
    'agora.form.privacy.friends': 'Conexiones',
    'agora.form.privacy.private': 'Privado',
    'agora.form.photo.title': '📸 Foto de Perfil',
    'agora.form.profession': 'Tu Profesión o Actividad Principal *',
    'agora.form.profession.placeholder': 'Ej: Psicóloga, Desarrollador, Chef, Artista, Consultor...',
    'agora.form.examples.title': 'Ejemplos de temas únicos:',
    'agora.form.examples.professional': 'Profesionales:',
    'agora.form.examples.professional.text': 'Charcutería artesanal, Piscicultura, Desarrollo de videojuegos',
    'agora.form.examples.creative': 'Creativos:',
    'agora.form.examples.creative.text': 'Tejido en crochet, Cerámica japonesa, Fotografía nocturna',
    'agora.form.examples.unique': 'Únicos:',
    'agora.form.examples.unique.text': 'Cultivo de orquídeas, Historia del jazz, Cocina molecular',
    'agora.form.topic1': '🎯 Tema 1: Tu expertise profesional o principal pasión *',
    'agora.form.topic1.placeholder': 'Ej: Desarrollo de aplicaciones móviles, Psicología clínica, Charcutería artesanal...',
    'agora.form.topic2': '🎨 Tema 2: Tu hobby o interés creativo favorito *',
    'agora.form.topic2.placeholder': 'Ej: Tejido en crochet, Fotografía de naturaleza, Cultivo de orquídeas...',
    'agora.form.topic3': '🌱 Tema 3: Algo que quieres aprender o explorar *',
    'agora.form.topic3.placeholder': 'Ej: Piscicultura artesanal, Historia del jazz, Cocina molecular...',
    'agora.form.bio': 'Cuéntanos sobre ti y por qué te interesan estos 3 temas * (Mínimo 50 caracteres)',
    'agora.form.bio.placeholder': 'Describe brevemente quién eres y por qué te apasionan los 3 temas que elegiste. Esto ayudará a otros a conectar contigo de manera más auténtica...',
    'agora.form.bio.min': 'caracteres mínimo',
    'agora.form.location': 'Ubicación *',
    'agora.form.location.placeholder': 'Ciudad, País',
    'agora.form.languages': 'Idiomas que Hablas',
    'agora.form.languages.placeholder': 'Español, Inglés, Francés...',
    'agora.form.linkedin': 'LinkedIn (Opcional)',
    'agora.form.linkedin.placeholder': 'https://linkedin.com/in/tu-perfil',
    'agora.form.website': 'Sitio Web Personal (Opcional)',
    'agora.form.website.placeholder': 'https://tu-sitio-web.com',
    'agora.form.goals': '¿Qué buscas en el Ágora? * (Selecciona todos los que apliquen)',
    'agora.form.availability': 'Disponibilidad para Conexiones',
    'agora.form.availability.very.active': 'Muy Activo (Varias veces al día)',
    'agora.form.availability.active': 'Activo (Una vez al día)',
    'agora.form.availability.flexible': 'Flexible (Varias veces por semana)',
    'agora.form.availability.occasional': 'Ocasional (Una vez por semana)',
    'agora.form.availability.limited': 'Limitado (Cuando sea necesario)',
    'agora.form.wb.seller.title': '¿También vendes productos o servicios?',
    'agora.form.wb.seller.yes': 'Sí, también vendo en World Boulevard',
    'agora.form.wb.seller.description': 'Tu perfil mostrará el logo WB 🟢 y podrás vender tus productos/servicios en World Boulevard',
    'agora.form.wb.benefits': 'Beneficios:',
    'agora.form.wb.benefits.text': 'Perfil comercial, Galería multimedia, Chat directo con clientes, Geolocalización inteligente',
    'agora.form.welcome.title': '¡Bienvenido al Ágora!',
    'agora.form.welcome.1': 'Conexiones auténticas',
    'agora.form.welcome.1.text': 'basadas en tus 3 temas únicos',
    'agora.form.welcome.2': 'Chat IA contextual',
    'agora.form.welcome.2.text': 'especializado en tus áreas de interés',
    'agora.form.welcome.3': 'Perfil con foto',
    'agora.form.welcome.3.text': 'para conexiones más humanas',
    'agora.form.welcome.4': 'Matching inteligente',
    'agora.form.welcome.4.text': 'con personas afines',
    'agora.form.welcome.5': 'Intercambio de conocimientos',
    'agora.form.welcome.5.text': 'únicos y especializados',
    'agora.form.success': '¡Bienvenido al Ágora! Tu perfil ha sido creado exitosamente.',
    'agora.form.success.photo': '¡Bienvenido al Ágora! Tu perfil con foto ha sido creado exitosamente. 🏛️✨',
    'agora.form.error': 'Error al crear la cuenta. Inténtalo de nuevo.',
    'agora.form.error.fullname': 'Nombre completo es requerido',
    'agora.form.error.email': 'Email es requerido',
    'agora.form.error.email.invalid': 'Email inválido',
    'agora.form.error.password': 'Contraseña es requerida',
    'agora.form.error.password.min': 'Mínimo 6 caracteres',
    'agora.form.error.password.match': 'Las contraseñas no coinciden',
    'agora.form.error.profession': 'Tu profesión es requerida',
    'agora.form.error.topic1': 'El primer tema es requerido',
    'agora.form.error.topic2': 'El segundo tema es requerido',
    'agora.form.error.topic3': 'El tercer tema es requerido',
    'agora.form.error.bio': 'Biografía es requerida',
    'agora.form.error.bio.min': 'La biografía debe tener al menos 50 caracteres',
    'agora.form.error.location': 'Ubicación es requerida',
    'agora.form.error.goals': 'Selecciona al menos un objetivo de conexión',

    // CONNECTION_GOALS options
    'agora.form.goal.networking.profesional': 'Networking Profesional',
    'agora.form.goal.intercambio.de.conocimientos': 'Intercambio de Conocimientos',
    'agora.form.goal.colaboraciones.creativas': 'Colaboraciones Creativas',
    'agora.form.goal.mentoring.(dar.o.recibir)': 'Mentoring (Dar o Recibir)',
    'agora.form.goal.proyectos.conjuntos': 'Proyectos Conjuntos',
    'agora.form.goal.amistad.intelectual': 'Amistad Intelectual',
    'agora.form.goal.desarrollo.de.negocios': 'Desarrollo de Negocios',
    'agora.form.goal.aprendizaje.continuo': 'Aprendizaje Continuo',

    // LOOKING_FOR_OPTIONS
    'agora.form.looking.conexiones.profesionales': 'Conexiones Profesionales',
    'agora.form.looking.amistad.intelectual': 'Amistad Intelectual',
    'agora.form.looking.colaboraciones.creativas': 'Colaboraciones Creativas',
    'agora.form.looking.intercambio.de.conocimientos': 'Intercambio de Conocimientos',
    'agora.form.looking.mentoring': 'Mentoring',
    'agora.form.looking.proyectos.conjuntos': 'Proyectos Conjuntos',
    'agora.form.looking.networking': 'Networking',
    'agora.form.looking.conversaciones.profundas': 'Conversaciones Profundas',

    // Boulevard Registration Form
    'boulevard.form.title': 'Registrar mi Negocio',
    'boulevard.form.subtitle': 'Crea tu espacio comercial en World Boulevard',
    'boulevard.form.cancel': 'Cancelar',
    'boulevard.form.submit': '🛍️ Registrar en World Boulevard',
    'boulevard.form.business.name': 'Nombre del Negocio *',
    'boulevard.form.business.name.placeholder': 'Ej: Cocina Creativa María Santos',
    'boulevard.form.category': 'Categoría *',
    'boulevard.form.category.select': 'Seleccionar categoría',
    'boulevard.form.category.gastronomy': 'Gastronomía',
    'boulevard.form.category.technology': 'Tecnología',
    'boulevard.form.category.health': 'Salud y Bienestar',
    'boulevard.form.category.education': 'Educación',
    'boulevard.form.category.art': 'Arte y Cultura',
    'boulevard.form.category.services': 'Servicios Profesionales',
    'boulevard.form.category.music': 'Música y Audio',
    'boulevard.form.category.design': 'Diseño y Creatividad',
    'boulevard.form.category.retail': 'Retail y Comercio',
    'boulevard.form.category.other': 'Otros',
    'boulevard.form.description': 'Descripción del Negocio *',
    'boulevard.form.description.placeholder': 'Describe tu negocio, qué lo hace único, tu experiencia y especialización...',
    'boulevard.form.products': 'Productos y Servicios *',
    'boulevard.form.products.placeholder': 'Lista tus principales productos o servicios (separados por comas)',
    'boulevard.form.email': 'Email de Contacto *',
    'boulevard.form.phone': 'Teléfono *',
    'boulevard.form.phone.placeholder': '+34 600 000 000',
    'boulevard.form.website': 'Sitio Web (Opcional)',
    'boulevard.form.website.placeholder': 'https://...',
    'boulevard.form.location': 'Ubicación *',
    'boulevard.form.location.placeholder': 'Ciudad, País',
    'boulevard.form.target': '¿A quién está dirigido tu negocio?',
    'boulevard.form.target.placeholder': 'Ej: Profesionales tech, Familias, Empresas, Artistas...',
    'boulevard.form.experience': 'Años de Experiencia',
    'boulevard.form.experience.select': 'Seleccionar experiencia',
    'boulevard.form.experience.less1': 'Menos de 1 año',
    'boulevard.form.experience.1to3': '1-3 años',
    'boulevard.form.experience.3to5': '3-5 años',
    'boulevard.form.experience.5to10': '5-10 años',
    'boulevard.form.experience.10to15': '10-15 años',
    'boulevard.form.experience.more15': 'Más de 15 años',
    'boulevard.form.goals.title': '¿Qué esperas lograr en World Boulevard?',
    'boulevard.form.goals.placeholder': 'Ej: Conectar con clientes locales, expandir mi red profesional, mostrar mi trabajo...',
    'boulevard.form.includes.title': 'Tu espacio en World Boulevard incluye:',
    'boulevard.form.includes.1': 'Perfil comercial destacado',
    'boulevard.form.includes.2': 'Galería multimedia expandible',
    'boulevard.form.includes.3': 'Chat directo con clientes',
    'boulevard.form.includes.4': 'Geolocalización inteligente',
    'boulevard.form.includes.5': 'Analytics de interacciones',
    'boulevard.form.includes.6': 'Certificación "Comercio Orgánico"',
    'boulevard.form.philosophy.title': 'Filosofía World Boulevard',
    'boulevard.form.philosophy.text': 'En World Boulevard creemos en el crecimiento orgánico y auténtico. Tu negocio crecerá por la calidad de tus productos/servicios y la autenticidad de tus conexiones, no por algoritmos manipulativos.',
    'boulevard.form.success': '¡Solicitud de registro enviada! Te contactaremos pronto para configurar tu espacio en World Boulevard. 🛍️✨',
    'boulevard.form.success.immediate': '¡Perfil creado exitosamente!',
    'boulevard.form.success.visible': 'Tu negocio ya está visible en World Boulevard para todos los usuarios.',
    'boulevard.form.submitting': 'Creando perfil...',
    'boulevard.form.error': 'Error al crear el negocio. Por favor intenta de nuevo.',
    'boulevard.form.error.generic': 'Ocurrió un error inesperado. Por favor intenta de nuevo.',
    'boulevard.form.scroll.help': '👇 Usa cremallera para navegar',
    'boulevard.form.scroll.complete': '✅ Formulario completo',
    'boulevard.form.scroll.top': 'Ir al inicio',
    'boulevard.form.scroll.bottom': 'Ir al final',

    // WB Profile Editor
    'wb.edit.title': 'Editar Perfil de Negocio',
    'wb.edit.save': 'Guardar Cambios',
    'wb.edit.saving': 'Guardando...',
    'wb.edit.success': 'Perfil actualizado exitosamente',
    'wb.edit.avatar.title': 'Logo / Imagen de Perfil',
    'wb.edit.gallery.title': 'Galería Multimedia',
    'wb.edit.gallery.description': 'Sube imágenes de tus productos, servicios o instalaciones. Puedes marcar una como destacada para el carrusel.',
    'wb.edit.button': 'Editar Perfil',

    // Personal Profile Editor
    'profile.edit.title': 'Editar Perfil Personal',
    'profile.edit.save': 'Guardar Cambios',
    'profile.edit.saving': 'Guardando...',
    'profile.edit.success': 'Perfil actualizado exitosamente',
    'profile.edit.avatar.title': 'Foto de Perfil',
    'profile.edit.cover.title': 'Imagen de Portada',
    'profile.edit.cover.description': 'Imagen que aparece en la parte superior de tu perfil',
    'profile.edit.gallery.title': 'Galería Personal',
    'profile.edit.gallery.description': 'Sube fotos de tus momentos, viajes, proyectos o lo que quieras compartir',
    'profile.form.name': 'Nombre Completo',
    'profile.form.profession': 'Profesión',
    'profile.form.bio': 'Biografía',
    'profile.form.location': 'Ubicación',
    'profile.form.interests': 'Intereses',
    'profile.form.cancel': 'Cancelar',

    // Post Creator
    'post.create.title': 'Crear Publicación',
    'post.create.type': 'Tipo de contenido',
    'post.type.image': 'Imagen',
    'post.type.video': 'Video',
    'post.create.upload.image': 'Sube tu imagen',
    'post.create.caption': 'Descripción',
    'post.caption.placeholder': 'Escribe algo sobre esta publicación...',
    'post.create.tags': 'Etiquetas',
    'post.tags.help': 'Separados por comas. Ayudan a que otros encuentren tu contenido.',
    'post.visibility.public': 'Publicación pública',
    'post.visibility.public.description': 'Todos los usuarios de Agora podrán ver esta publicación',
    'post.form.cancel': 'Cancelar',
    'post.publish': 'Publicar',
    'post.creating': 'Publicando...',
    'post.video.coming.soon': 'Videos cortos próximamente',
    'post.video.description': 'Pronto podrás compartir videos de hasta 60 segundos',

    // Commercial Space Form
    'commercial.form.title': '💼 Espacios Comerciales',
    'commercial.form.subtitle': 'Solicita tu espacio en World Boulevard',
    'commercial.form.business.name': 'Nombre del Negocio',
    'commercial.form.category': 'Categoría',
    'commercial.form.category.select': 'Seleccionar categoría',
    'commercial.form.category.gastronomy': 'Gastronomía',
    'commercial.form.category.technology': 'Tecnología',
    'commercial.form.category.health': 'Salud y Bienestar',
    'commercial.form.category.education': 'Educación',
    'commercial.form.category.art': 'Arte y Cultura',
    'commercial.form.category.services': 'Servicios Profesionales',
    'commercial.form.category.retail': 'Retail y Comercio',
    'commercial.form.category.other': 'Otros',
    'commercial.form.description': 'Descripción del Negocio',
    'commercial.form.description.placeholder': 'Describe tu negocio, productos o servicios...',
    'commercial.form.email': 'Email de Contacto',
    'commercial.form.phone': 'Teléfono',
    'commercial.form.website': 'Sitio Web',
    'commercial.form.website.placeholder': 'https://...',
    'commercial.form.location': 'Ubicación',
    'commercial.form.location.placeholder': 'Ciudad, País',
    'commercial.form.includes.title': '¿Qué incluye tu espacio comercial?',
    'commercial.form.includes.1': 'Perfil destacado en World Boulevard',
    'commercial.form.includes.2': 'Chat directo con clientes potenciales',
    'commercial.form.includes.3': 'Geolocalización para clientes cercanos',
    'commercial.form.includes.4': 'Analytics de interacciones y visitas',
    'commercial.form.includes.5': 'Soporte personalizado para optimizar tu presencia',
    'commercial.form.submit': 'Solicitar Espacio Comercial',
    'commercial.form.success': '¡Solicitud enviada! Te contactaremos pronto para configurar tu espacio comercial.',

    // Common
    'loading': 'Cargando...',
    'error': 'Error',
    'success': 'Éxito',
    'demo.mode': 'Modo Demo',
    'natural.intelligence': 'La Inteligencia Natural',
    'connect': 'Conectar',
    'contact': 'Contactar',
    'message': 'Mensaje',
    'call': 'Llamar',
    'video.call': 'Videollamada',
    'voice.message': 'Mensaje de voz',
    'send': 'Enviar',
    'like': 'Me gusta',
    'comment': 'Comentar',
    'share': 'Compartir',
    'view.more': 'Ver más',
    'show.less': 'Mostrar menos',
    'read.more': 'Leer más',
    'back': 'Atrás',
    'next': 'Siguiente',
    'previous': 'Anterior',
    'finish': 'Finalizar',
    'continue': 'Continuar',
    'skip': 'Omitir',
    'done': 'Hecho',
    'yes': 'Sí',
    'no': 'No',
    'maybe': 'Tal vez',
    'online': 'En línea',
    'offline': 'Desconectado',
    'active': 'Activo',
    'inactive': 'Inactivo'
  },
  
  en: {
    // Header and navigation
    'nav.agora': '🏛️ Agora',
    'nav.boulevard': '🛍️ Boulevard',
    'nav.dashboard': '📊 Dashboard',
    'nav.home': '🏠 Home',
    'nav.install': '📱 Install App',
    'nav.login': 'Sign In',
    'nav.help': 'Help',
    
    // Hero Section
    'hero.title': 'HUMANBIBLIO',
    'hero.subtitle1': 'Free your communication',
    'hero.subtitle2': 'Connect consciously',
    'hero.subtitle3': 'Grow organically',
    'hero.subtitle4': 'Live authentically',
    'hero.description': 'Free your communication from manipulative algorithms. Connect authentically with people and businesses.',
    'hero.description2': 'Free and organic communication.',
    'hero.cta.agora': '🏛️ Enter the Agora',
    'hero.cta.boulevard': '🛍️ Explore Boulevard',
    'hero.scroll': 'Discover more below',
    'hero.stat.ai': 'AI Personalities',
    'hero.stat.manipulation': 'No Manipulation',
    'hero.stat.connections': 'Authentic Connections',
    'hero.stat.app': 'Native App',
    
    // Agora
    'agora.title': '🏛️ Agora - The Meeting of Brilliant Minds',
    'agora.description': 'Connect with extraordinary people. Discover professionals and experts who can enrich your life with contextual AI.',
    'agora.join': '🏛️ Join the Agora',
    'agora.join.subtitle': 'Create your profile with 3 unique topics + discreet dating info',
    'agora.manifesto.title': 'Natural Intelligence',
    'agora.manifesto.subtitle': 'We liberate human communication from algorithmic manipulation',
    'agora.manifesto.description': 'Here, YOU decide who to connect with, when and how.',
    'agora.profiles.tab': '👥 Profiles',
    'agora.universe.tab': '🌌 We Are Not Alone',
    'agora.search.placeholder': 'Search people, professions, skills, interests...',
    'agora.wb.title': 'Do you sell products or services?',
    'agora.wb.description': 'Buy your commercial space in World Boulevard',
    'agora.wb.button': '🛍️ Buy WB Space',
    'agora.wb.select.user': 'Which user do you want to buy commercial space for?',
    'agora.wb.plan.basic': 'Basic Plan',
    'agora.wb.plan.premium': 'Premium Plan',
    'agora.wb.plan.enterprise': 'Enterprise Plan',
    'agora.wb.benefits.title': '🎯 World Boulevard Benefits:',
    'agora.wb.benefits.profile': '🛍️ Professional business profile',
    'agora.wb.benefits.gallery': '📸 Expandable multimedia gallery',
    'agora.wb.benefits.chat': '💬 Direct chat with clients',
    'agora.wb.benefits.geo': '🌍 Intelligent geolocation',
    'agora.wb.benefits.analytics': '📊 Interaction analytics',
    'agora.wb.benefits.carousel': '🎠 Advertising carousel',
    'agora.mindmate.title': 'Find your mind mate!',
    'agora.mindmate.description': 'Deep intellectual and conscious connections',
    'agora.mindmate.button': '🧠 Find Mind Mate',
    'agora.universe.title': 'You Are Not Alone (YANA)',
    'agora.universe.description': 'Someone wants to talk to you',
    'agora.universe.button': '🌍 Connect with Real Humans',
    
    // World Boulevard
    'boulevard.title': '🛍️ World Boulevard - Organic Commerce',
    'boulevard.description': 'Discover unique and authentic businesses. Connect directly with exceptional entrepreneurs.',
    'boulevard.register': '🛍️ Register my Business',
    'boulevard.register.subtitle': 'Create your commercial space in World Boulevard',
    'boulevard.featured.title': '⭐ Featured Businesses',
    'boulevard.featured.description': 'Discover the most authentic and unique businesses in World Boulevard',
    'boulevard.sponsors.title': '🏆 Featured Funders and Partners',
    'boulevard.sponsors.description': 'Meet the visionaries driving innovation in HUMANBIBLIO',
    'boulevard.tabs.businesses': '🛍️ Featured Businesses',
    'boulevard.tabs.sponsors': '🏆 Funders and Partners',
    'boulevard.search.placeholder': 'Search businesses, categories, products, services...',
    'boulevard.contact.now': '💬 Contact Now',
    'boulevard.call': '📞 Call',
    'boulevard.website': '🌐 Website',
    'boulevard.location': '📍 Location',
    'boulevard.badge.featured': '⭐ Featured',
    'boulevard.organic.certified': 'Certified Organic Commerce',
    'boulevard.organic.growth': 'Authentic growth',
    'boulevard.organic.no_ads': 'No forced advertising',
    'boulevard.organic.verified': 'Verified by HUMANBIBLIO',
    'boulevard.organic.direct': 'Direct communication',
    'boulevard.info.organic': 'Organic Commerce',
    'boulevard.info.direct': 'Direct Connection',
    'boulevard.info.no_intermediaries': 'No Intermediaries',
    'boulevard.autoplay.pause': 'Pause autoplay',
    'boulevard.autoplay.play': 'Activate autoplay',
    'boulevard.sponsor.promotion.title': '💡 Want to appear here?',
    'boulevard.sponsor.promotion.description': 'Fund innovative projects in "You Are Not Alone (YANA)" and get premium recognition in World Boulevard',
    'boulevard.sponsor.promotion.button': '🌌 Explore Projects to Fund',
    'boulevard.sponsor.empty.title': 'Be the First Featured Funder',
    'boulevard.sponsor.empty.description': 'Fund innovative projects and appear in this premium carousel',
    'boulevard.sponsor.empty.button': '🌟 Become a Funder',
    'boulevard.sponsor.empty.alert': '🚀 Go to "You Are Not Alone (YANA)" to fund projects and appear here',
    'boulevard.sponsor.level.platinum': 'Platinum Funder',
    'boulevard.sponsor.level.gold': 'Gold Funder',
    'boulevard.sponsor.level.silver': 'Silver Funder',
    'boulevard.sponsor.level.bronze': 'Bronze Funder',
    'boulevard.sponsor.funded': 'funded',
    'boulevard.sponsor.active.message': 'is an active funder supporting innovative projects in HUMANBIBLIO.',
    'boulevard.sponsor.impact.title': 'Impact as a funder:',
    'boulevard.sponsor.impact.projects': 'funded projects',
    'boulevard.sponsor.impact.entrepreneurs': 'supported entrepreneurs',
    'boulevard.sponsor.impact.total': 'total impact',
    'boulevard.sponsor.button.business': '🛍️ View Business on Boulevard',
    'boulevard.sponsor.button.profile': '👤 View Profile on Agora',
    'boulevard.sponsor.button.contact': '💬 Contact',
    'boulevard.sponsor.button.collaborate': '🤝 Collaborate',
    'boulevard.sponsor.alert.contact': '💬 Starting conversation with',
    'boulevard.sponsor.alert.collaborate': '🤝 Exploring collaborations with',
    'boulevard.sponsor.info.featured': 'Featured Funders',
    'boulevard.sponsor.info.investment': 'Smart Investment',
    'boulevard.sponsor.info.recognition': 'Premium Recognition',
    'funder.total.funded': 'Total funded',
    'funder.count.singular': 'funder',
    'funder.count.plural': 'funders',
    'funder.project.success': 'Successfully funded project',
    'funder.funded.by': '🏆 Funded by',

    // Expanded Business Profile
    'expanded.business.tab.info': 'Information',
    'expanded.business.tab.reviews': 'Reviews',
    'expanded.business.reviews.count': 'reviews',
    'expanded.business.services.title': 'Services and Products',

    // Business Card
    'business.card.services': 'Services',
    'business.card.view': 'View Profile',

    // User Card
    'user.card.interests': 'Interests',
    'user.card.view': 'View Profile',

    // Project Card
    'project.card.category': 'Category',
    'project.card.funding': 'Funding',
    'project.card.likes': 'Likes',
    'project.card.comments': 'Comments',

    // Dashboard
    'dashboard.title': '📊 Personal Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': '📊 Overview',
    'dashboard.nearby': '🌍 Near Me',
    'dashboard.matching': '🎯 AI Matching',
    'dashboard.connections': 'Connections',
    'dashboard.messages': 'Messages',
    'dashboard.rating': 'Rating',
    'dashboard.recent.activity': 'Recent Activity',
    'dashboard.new.connection': 'New connection with',
    'dashboard.message.from': 'Message from',
    'dashboard.hours.ago': '{hours} hours ago',
    'dashboard.nearby.title': '🌍 Near Me',
    'dashboard.nearby.found': 'items found within',
    'dashboard.nearby.radius': 'Radius:',
    'dashboard.nearby.map': '🗺️ Map',
    'dashboard.nearby.list': '📋 List',
    'dashboard.matching.title': '🎯 AI Matching',
    'dashboard.matching.description': 'Our AI algorithm has analyzed your profile and found the best connections for you',
    'dashboard.matching.average': 'Average Compatibility',
    'dashboard.matching.based': 'Based on {count} analyzed profiles',
    
    // Impact Metrics
    'impact.title': '📊 Real Impact in Numbers',
    'impact.subtitle': 'Pilot Metrics: Authentic connections, not wasted time.',
    'impact.connections.label': 'Pilot Users',
    'impact.connections.desc': 'People testing the platform',
    'impact.messages.label': 'Conversations',
    'impact.messages.desc': 'Genuine exchanges during pilot',
    'impact.businesses.label': 'Registered Businesses',
    'impact.businesses.desc': 'Stores in World Boulevard',
    'impact.satisfaction.label': 'Satisfaction',
    'impact.satisfaction.desc': 'Positive feedback from pilot users',

    // Features
    'features.title': '🌟 Revolutionary Features',
    'features.description': 'Every feature is designed to unleash your human potential, not to capture your attention.',
    'features.amplifies': 'Technology that amplifies your humanity',
    'features.ai.title': 'Contextual AI',
    'features.ai.description': 'Intelligent conversations that adapt to each person\'s expertise',
    'features.ai.detail1': '4 specialized personalities',
    'features.ai.detail2': 'Responses based on profession',
    'features.ai.detail3': 'Sentiment analysis',
    'features.ai.detail4': 'Conversational memory',
    'features.connections.title': 'Conscious Connections',
    'features.connections.description': 'Every connection is intentional, without manipulative algorithms',
    'features.connections.detail1': 'Clear intention flow',
    'features.connections.detail2': 'Quality over quantity',
    'features.connections.detail3': 'No designed addiction',
    'features.connections.detail4': 'Authentic communication',
    'features.matching.title': 'Intelligent Matching',
    'features.matching.description': 'Algorithms that connect by real compatibility, not engagement',
    'features.matching.detail1': 'Interest analysis',
    'features.matching.detail2': 'Professional compatibility',
    'features.matching.detail3': 'Geographic proximity',
    'features.matching.detail4': 'Common goals',
    'features.pwa.title': 'Native Experience',
    'features.pwa.description': 'Installable PWA that works like a native app',
    'features.pwa.detail1': 'Direct installation',
    'features.pwa.detail2': 'Works offline',
    'features.pwa.detail3': 'Push notifications',
    'features.pwa.detail4': 'Quick access',
    'features.geo.title': 'Intelligent Geolocation',
    'features.geo.description': 'Discover amazing people and businesses near you',
    'features.geo.detail1': 'Interactive map',
    'features.geo.detail2': 'Distance filters',
    'features.geo.detail3': 'Protected privacy',
    'features.geo.detail4': 'Local search',
    'features.commerce.title': 'Organic Commerce',
    'features.commerce.description': 'Businesses that grow authentically, without forced advertising',
    'features.commerce.detail1': 'Natural growth',
    'features.commerce.detail2': 'No intermediaries',
    'features.commerce.detail3': 'Direct relationships',
    'features.commerce.detail4': 'Conscious commerce',
    
    // Comparison
    'comparison.title': '⚔️ HUMANBIBLIO vs Traditional Networks',
    'comparison.subtitle': 'The difference is revolutionary',
    'comparison.traditional': 'Traditional Networks',
    'comparison.humanbiblio': 'HUMANBIBLIO',
    
    // Traditional Networks
    'traditional.addiction.title': 'Designed for Addiction',
    'traditional.addiction.desc': 'Attention economy - your time is their product',
    'traditional.addiction.1': 'Infinite scroll without end',
    'traditional.addiction.2': 'Constant notifications',
    'traditional.addiction.3': 'FOMO (Fear of Missing Out)',
    
    'traditional.algorithms.title': 'Manipulative Algorithms',
    'traditional.algorithms.desc': 'They decide what you see and when you see it',
    'traditional.algorithms.1': 'Opaque content filters',
    'traditional.algorithms.2': 'Engagement-based prioritization',
    'traditional.algorithms.3': 'Bias towards controversy',
    
    'traditional.ads.title': 'Intrusive Advertising',
    'traditional.ads.desc': 'Interrupts authentic connections',
    'traditional.ads.1': 'Ads between content',
    'traditional.ads.2': 'Invasive targeting',
    'traditional.ads.3': 'Data commercialization',
    
    'traditional.engagement.title': 'Artificial Engagement',
    'traditional.engagement.desc': 'Empty metrics without real meaning',
    'traditional.engagement.1': 'Likes as validation',
    'traditional.engagement.2': 'Competition for attention',
    'traditional.engagement.3': 'Incentivized superficiality',
    
    'traditional.data.title': 'Data as Product',
    'traditional.data.desc': 'Your privacy gets monetized',
    'traditional.data.1': 'Profiling without consent',
    'traditional.data.2': 'Third-party sales',
    'traditional.data.3': 'Lack of transparency',
    
    'traditional.result': 'Result: Discomfort + Addiction',
    'traditional.result.desc': 'Communication subverted by commercial interests',
    
    // HUMANBIBLIO
    'humanbiblio.authentic.title': 'Authentic Communication',
    'humanbiblio.authentic.desc': 'Sender → Receiver direct',
    'humanbiblio.authentic.1': 'Clear intention flow',
    'humanbiblio.authentic.2': 'Meaningful connections',
    'humanbiblio.authentic.3': 'No designed addiction',
    
    'humanbiblio.ai.title': 'AI as Tool',
    'humanbiblio.ai.desc': 'You maintain total control',
    'humanbiblio.ai.1': 'Specialized contextual AI',
    'humanbiblio.ai.2': 'Expertise-based responses',
    'humanbiblio.ai.3': 'Complete transparency',
    
    'humanbiblio.commerce.title': 'Organic Commerce',
    'humanbiblio.commerce.desc': 'Authentic growth without forced advertising',
    'humanbiblio.commerce.1': 'No intermediaries',
    'humanbiblio.commerce.2': 'Direct connection',
    'humanbiblio.commerce.3': 'Natural growth',
    
    'humanbiblio.authentic2.title': 'Real Authenticity',
    'humanbiblio.authentic2.desc': 'Genuine and meaningful connections',
    'humanbiblio.authentic2.1': 'Verified real profiles',
    'humanbiblio.authentic2.2': 'Deep conversations',
    'humanbiblio.authentic2.3': 'Lasting relationships',
    
    'humanbiblio.privacy.title': 'Respected Privacy',
    'humanbiblio.privacy.desc': 'Your data is yours and yours alone',
    'humanbiblio.privacy.1': 'Total data control',
    'humanbiblio.privacy.2': 'No third-party sales',
    'humanbiblio.privacy.3': 'Absolute transparency',
    
    'humanbiblio.result': 'Result: Wellbeing + Growth',
    'humanbiblio.result.desc': 'Authentic communication that amplifies your humanity',
    
    // Natural Intelligence Manifesto
    'manifesto.title': 'Natural Intelligence',
    'manifesto.subtitle': 'We liberate human communication from algorithmic manipulation',
    'manifesto.description': 'Here, YOU decide who to connect with, when and how.',
    'manifesto.problem.title': 'Traditional Networks',
    'manifesto.solution.title': 'HUMANBIBLIO',
    'manifesto.mission.title': 'Our Mission',
    'manifesto.mission.description': 'At HUMANBIBLIO, YOU control your communication, not algorithms. Every connection is intentional, every conversation is authentic, and every business grows freely and organically.',
    'manifesto.channel.problem': 'The channel is the sender: "Don\'t disconnect, pay attention to me!"',
    'manifesto.attention.economy': 'Attention economy: Your time = their product',
    'manifesto.intrusive.ads': 'Intrusive advertising: Interrupts real connections',
    'manifesto.cognitive.dissonance': 'Cognitive dissonance: Discomfort + addiction',
    'manifesto.subverted.communication': 'Subverted communication: Algorithms decide for you',
    'manifesto.authentic.communication': 'Authentic communication: Sender → Receiver direct',
    'manifesto.natural.intelligence': 'Natural Intelligence: Your judgment + AI as tool',
    'manifesto.organic.commerce': 'Organic commerce: No forced advertising',
    'manifesto.conscious.connections': 'Conscious connections: Quality over quantity',
    'manifesto.creative.freedom': 'Creative freedom: Authentic expansion',
    
    // Universe Section
    'universe.title': 'You Are Not Alone (YANA)',
    'universe.subtitle': 'While we search for extraterrestrial life, millions of humans live in loneliness. Someone right now wants to talk to you.',
    'universe.paradox.title': 'The Human Paradox',
    'universe.paradox.description': 'We spend billions searching for signals from outer space, but ignore the loneliness signals from millions of extraordinary people who are just one click away. HUMANBIBLIO solves this paradox.',
    'universe.tabs.explore': 'Explore Universe',
    'universe.tabs.together': 'Let\'s Do It Together',
    'universe.tabs.news': 'Trending',
    'universe.explore.title': 'Explore Universe',
    'universe.together.title': 'Let\'s Do It Together',
    'universe.news.title': 'Universe Trending',
    'universe.news.subtitle': 'The projects and ideas generating the most conversations in the community',
    'universe.publish.project': 'Publish My Project',
    'universe.most.popular': 'Most Popular Project',
    'universe.most.popular.subtitle': 'The project generating the most conversations',
    'universe.trending.projects': 'Trending Projects',
    'universe.community.impact': 'Community Impact',
    'universe.active.projects': 'Active Projects',
    'universe.total.likes': 'Total Likes',
    'universe.connections': 'Connections',
    'universe.seeking.partners': 'Seeking Partners',
    
    // Project Actions
    'project.like': 'I\'m Interested',
    'project.contact': 'Contact',
    'project.funded.by': 'Funded by',
    'project.looking.funding': 'Seeking Funding',
    'project.looking.partners': 'Seeking Partners',
    'project.looking.collaboration': 'Seeking Collaborators',
    'project.looking.discussion': 'Seeking Discussion',
    'project.published': 'Published',
    'project.likes': 'likes',
    'project.contacts': 'contacts',
    'project.conversations': 'conversations',
    
    // Call to Action Section
    'cta.title': '🌟 Join the Revolution',
    'cta.subtitle': 'Be part of the change towards more human and authentic digital communication',
    'cta.agora.title': 'The Agora',
    'cta.agora.desc': 'Connect with brilliant minds. Discover extraordinary professionals with contextual AI.',
    'cta.agora.feature1': 'Specialized AI Chat',
    'cta.agora.feature2': 'Intelligent Matching',
    'cta.agora.feature3': 'Multimedia Communication',
    'cta.agora.button': '🏛️ Enter the Agora',
    'cta.boulevard.title': 'World Boulevard',
    'cta.boulevard.desc': 'Discover unique businesses. Organic commerce without manipulative advertising.',
    'cta.boulevard.feature1': 'Organic Commerce',
    'cta.boulevard.feature2': 'Multimedia Gallery',
    'cta.boulevard.feature3': 'Direct Connection',
    'cta.boulevard.button': '🛍️ Explore Boulevard',
    'cta.dashboard.title': 'Dashboard',
    'cta.dashboard.desc': 'Your personal control center. Statistics, geolocation, and AI matching.',
    'cta.dashboard.feature1': 'Personal Analytics',
    'cta.dashboard.feature2': 'Near Me Explorer',
    'cta.dashboard.feature3': 'AI Matching',
    'cta.dashboard.button': '📊 Open Dashboard',
    'cta.future.title': 'The Future of Digital Communication',
    'cta.future.desc': 'HUMANBIBLIO is not just a platform, it\'s a movement towards Natural Intelligence - where technology amplifies our humanity instead of replacing it.',

    // Action Buttons
    'action.wb.title': 'Do you sell products or services?',
    'action.wb.desc': 'Buy your commercial space in World Boulevard',
    'action.wb.button': '🛍️ Buy WB Space',
    
    'action.soulmate.title': 'Find your mind mate!',
    'action.soulmate.desc': 'Deep intellectual compatibility and conscious connections',
    'action.soulmate.button': '🧠 Find Mind Mate',
    
    'action.universe.title': 'You Are Not Alone (YANA)',
    'action.universe.desc': 'Someone wants to talk to you',
    'action.universe.button': '🌍 Connect with Real Humans',
    
    // Forms and Modals
    'form.name': 'Full Name',
    'form.email': 'Email',
    'form.password': 'Password',
    'form.profession': 'Profession',
    'form.bio': 'Biography',
    'form.location': 'Location',
    'form.interests': 'Interests',
    'form.cancel': 'Cancel',
    'form.submit': 'Submit',
    'form.save': 'Save',
    'form.close': 'Close',
    'form.required': 'Required',
    'form.optional': 'Optional',
    
    // Business Forms
    'business.form.title': 'Register my Business',
    'business.form.subtitle': 'Create your commercial space in World Boulevard',
    'business.form.name': 'Business Name',
    'business.form.category': 'Category',
    'business.form.description': 'Business Description',
    'business.form.products': 'Products and Services',
    'business.form.contact.email': 'Contact Email',
    'business.form.contact.phone': 'Phone',
    'business.form.website': 'Website',
    'business.form.target': 'Who is your business for?',
    'business.form.experience': 'Years of Experience',
    'business.form.goals': 'What do you hope to achieve in World Boulevard?',
    'business.form.includes.title': 'Your World Boulevard space includes:',
    'business.form.includes.profile': 'Featured business profile',
    'business.form.includes.gallery': 'Expandable multimedia gallery',
    'business.form.includes.chat': 'Direct chat with clients',
    'business.form.includes.geo': 'Intelligent geolocation',
    'business.form.includes.analytics': 'Interaction analytics',
    'business.form.includes.certification': '"Organic Commerce" certification',
    'business.form.philosophy.title': 'World Boulevard Philosophy',
    'business.form.philosophy.description': 'At World Boulevard we believe in organic and authentic growth. Your business will grow through the quality of your products/services and the authenticity of your connections, not through manipulative algorithms.',
    
    // User Cards
    'user.card.message': 'Send message',
    'user.card.call': 'Call',
    'user.card.video': 'Video call',
    'user.card.voice': 'Voice message',
    'user.card.wb.sells': 'Sells',
    'user.card.wb.view': 'View {name}\'s business profile in World Boulevard',

    // Business Cards
    'business.card.contact': 'Contact',
    'business.card.call': 'Call',
    'business.card.website': 'Website',
    'business.card.location': 'Location',
    'business.card.rating': 'Average rating',
    'business.card.reviews': 'reviews',

    // Communication
    'communication.hub.title': 'How do you want to communicate?',
    'communication.chat.title': 'Intelligent Chat',
    'communication.chat.description': 'Specialized contextual AI',
    'communication.voice.title': 'Voice Call',
    'communication.voice.description': 'Real-time conversation',
    'communication.video.title': 'Video Call',
    'communication.video.description': 'Complete visual connection',
    'communication.audio.title': 'Voice Message',
    'communication.audio.description': 'Personal audio recording',
    'communication.natural.intelligence': 'Natural Intelligence',
    'communication.natural.description': 'Every conversation is authentic, without manipulative algorithms. AI responds according to the person\'s real expertise.',
    
    // Search and Filters
    'search.loading': 'Searching...',
    'search.results': 'results for',
    'search.no.results': 'No results found',
    'search.suggestions': 'Suggestions',
    'search.recent': 'Recent searches',
    'search.filters': 'Advanced filters',
    'search.clear': 'Clear search',
    'search.apply': 'Apply filters',
    'search.all.locations': 'All locations',
    'search.add.interest': 'Add interest',
    
    // Geolocation
    'geo.title': 'Discover what\'s nearby',
    'geo.description': 'Enable geolocation to find amazing people and businesses near you',
    'geo.activate': '🌍 Enable Geolocation',
    'geo.permission.title': 'Discover what\'s nearby',
    'geo.permission.description': 'HUMANBIBLIO can show you people and businesses near your location. Your privacy is protected.',
    'geo.privacy.title': 'Your privacy is important',
    'geo.privacy.local': 'Only to show nearby results',
    'geo.privacy.no.store': 'We don\'t store your location',
    'geo.privacy.disable': 'You can disable it anytime',
    'geo.privacy.no.share': 'We don\'t share data with third parties',
    'geo.discover.title': 'What you can discover',
    'geo.discover.professionals': 'Professionals and experts in your area',
    'geo.discover.businesses': 'Unique and authentic local businesses',
    'geo.discover.events': 'Nearby events and opportunities',
    'geo.discover.connections': 'Meaningful connections in your city',
    
    // PWA
    'pwa.install.title': 'Install HUMANBIBLIO!',
    'pwa.install.description': 'Get the complete experience by installing our PWA. It works like a native app:',
    'pwa.install.faster': 'Faster access from your home screen',
    'pwa.install.offline': 'Works without internet connection',
    'pwa.install.notifications': 'Push notifications (coming soon)',
    'pwa.install.native': 'Native app experience',
    'pwa.install.button': '📱 Install App',
    'pwa.install.later': 'Not now',
    'pwa.install.tip': 'If you close this window, you can reopen it with the "📱 Install App" button in the header.',

    // Auth Modal
    'auth.login.title': '🔑 Sign In',
    'auth.signup.title': '📝 Create Account',
    'auth.login.subtitle': 'Access your account',
    'auth.signup.subtitle': 'Join HUMANBIBLIO',
    'auth.fullname': 'Full name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login.button': 'Sign In',
    'auth.signup.button': 'Create Account',
    'auth.processing': 'Processing...',
    'auth.no.account': 'Don\'t have an account? Sign up',
    'auth.have.account': 'Already have an account? Sign in',
    'auth.looking.for': 'Looking for something specific?',
    'auth.join.agora': '🏛️ Join the Agora (People)',
    'auth.register.business': '🛍️ Register Business (World Boulevard)',
    'auth.required': 'You must sign in to create a business',

    // Agora Registration Form
    'agora.form.title': '🏛️ Join the Agora',
    'agora.form.subtitle': 'The Meeting of Extraordinary Minds',
    'agora.form.step': 'Step',
    'agora.form.of': 'of',
    'agora.form.completed': 'completed',
    'agora.form.previous': '← Previous',
    'agora.form.next': 'Next →',
    'agora.form.join': '🏛️ Join the Agora',
    'agora.form.creating': 'Creating account...',
    'agora.form.step1.title': 'Basic Information',
    'agora.form.step1.subtitle': 'Let\'s start with your fundamental data',
    'agora.form.step2.title': 'Your 3 Exchange Topics',
    'agora.form.step2.subtitle': 'Freely write the 3 topics you love to talk about',
    'agora.form.step3.title': 'Finalize Profile',
    'agora.form.step3.subtitle': 'Additional information and connection goals',
    'agora.form.fullname': 'Full Name *',
    'agora.form.fullname.placeholder': 'Your full name',
    'agora.form.email': 'Email *',
    'agora.form.email.placeholder': 'you@email.com',
    'agora.form.password': 'Password *',
    'agora.form.password.placeholder': 'Minimum 6 characters',
    'agora.form.confirm.password': 'Confirm Password *',
    'agora.form.confirm.password.placeholder': 'Repeat your password',
    'agora.form.dating.title': 'Personal Information (Optional and Discreet)',
    'agora.form.age': 'Age (Optional)',
    'agora.form.age.not.say': 'Prefer not to say',
    'agora.form.age.18.25': '18-25 years',
    'agora.form.age.26.35': '26-35 years',
    'agora.form.age.36.45': '36-45 years',
    'agora.form.age.46.55': '46-55 years',
    'agora.form.age.56plus': '56+ years',
    'agora.form.relationship': 'Relationship Status (Optional)',
    'agora.form.relationship.not.say': 'Prefer not to say',
    'agora.form.relationship.single': 'Single',
    'agora.form.relationship.dating': 'In a relationship',
    'agora.form.relationship.married': 'Married',
    'agora.form.relationship.divorced': 'Divorced',
    'agora.form.relationship.widowed': 'Widowed',
    'agora.form.relationship.complicated': 'It\'s complicated',
    'agora.form.looking.for': 'What are you looking for in HUMANBIBLIO? (Optional - Select all that apply)',
    'agora.form.privacy.level': 'Privacy Level',
    'agora.form.privacy.public': 'Public',
    'agora.form.privacy.friends': 'Connections',
    'agora.form.privacy.private': 'Private',
    'agora.form.photo.title': '📸 Profile Photo',
    'agora.form.profession': 'Your Profession or Main Activity *',
    'agora.form.profession.placeholder': 'E.g.: Psychologist, Developer, Chef, Artist, Consultant...',
    'agora.form.examples.title': 'Examples of unique topics:',
    'agora.form.examples.professional': 'Professional:',
    'agora.form.examples.professional.text': 'Artisanal charcuterie, Aquaculture, Video game development',
    'agora.form.examples.creative': 'Creative:',
    'agora.form.examples.creative.text': 'Crochet knitting, Japanese ceramics, Night photography',
    'agora.form.examples.unique': 'Unique:',
    'agora.form.examples.unique.text': 'Orchid cultivation, Jazz history, Molecular cuisine',
    'agora.form.topic1': '🎯 Topic 1: Your professional expertise or main passion *',
    'agora.form.topic1.placeholder': 'E.g.: Mobile app development, Clinical psychology, Artisanal charcuterie...',
    'agora.form.topic2': '🎨 Topic 2: Your hobby or favorite creative interest *',
    'agora.form.topic2.placeholder': 'E.g.: Crochet knitting, Nature photography, Orchid cultivation...',
    'agora.form.topic3': '🌱 Topic 3: Something you want to learn or explore *',
    'agora.form.topic3.placeholder': 'E.g.: Artisanal aquaculture, Jazz history, Molecular cuisine...',
    'agora.form.bio': 'Tell us about yourself and why you are interested in these 3 topics * (Minimum 50 characters)',
    'agora.form.bio.placeholder': 'Briefly describe who you are and why you are passionate about the 3 topics you chose. This will help others connect with you more authentically...',
    'agora.form.bio.min': 'minimum characters',
    'agora.form.location': 'Location *',
    'agora.form.location.placeholder': 'City, Country',
    'agora.form.languages': 'Languages You Speak',
    'agora.form.languages.placeholder': 'Spanish, English, French...',
    'agora.form.linkedin': 'LinkedIn (Optional)',
    'agora.form.linkedin.placeholder': 'https://linkedin.com/in/your-profile',
    'agora.form.website': 'Personal Website (Optional)',
    'agora.form.website.placeholder': 'https://your-website.com',
    'agora.form.goals': 'What are you looking for in the Agora? * (Select all that apply)',
    'agora.form.availability': 'Availability for Connections',
    'agora.form.availability.very.active': 'Very Active (Several times a day)',
    'agora.form.availability.active': 'Active (Once a day)',
    'agora.form.availability.flexible': 'Flexible (Several times a week)',
    'agora.form.availability.occasional': 'Occasional (Once a week)',
    'agora.form.availability.limited': 'Limited (When necessary)',
    'agora.form.wb.seller.title': 'Do you also sell products or services?',
    'agora.form.wb.seller.yes': 'Yes, I also sell on World Boulevard',
    'agora.form.wb.seller.description': 'Your profile will show the WB logo 🟢 and you can sell your products/services on World Boulevard',
    'agora.form.wb.benefits': 'Benefits:',
    'agora.form.wb.benefits.text': 'Business profile, Multimedia gallery, Direct chat with customers, Intelligent geolocation',
    'agora.form.welcome.title': 'Welcome to the Agora!',
    'agora.form.welcome.1': 'Authentic connections',
    'agora.form.welcome.1.text': 'based on your 3 unique topics',
    'agora.form.welcome.2': 'Contextual AI chat',
    'agora.form.welcome.2.text': 'specialized in your areas of interest',
    'agora.form.welcome.3': 'Profile with photo',
    'agora.form.welcome.3.text': 'for more human connections',
    'agora.form.welcome.4': 'Intelligent matching',
    'agora.form.welcome.4.text': 'with like-minded people',
    'agora.form.welcome.5': 'Knowledge exchange',
    'agora.form.welcome.5.text': 'unique and specialized',
    'agora.form.success': 'Welcome to the Agora! Your profile has been created successfully.',
    'agora.form.success.photo': 'Welcome to the Agora! Your profile with photo has been created successfully. 🏛️✨',
    'agora.form.error': 'Error creating account. Please try again.',
    'agora.form.error.fullname': 'Full name is required',
    'agora.form.error.email': 'Email is required',
    'agora.form.error.email.invalid': 'Invalid email',
    'agora.form.error.password': 'Password is required',
    'agora.form.error.password.min': 'Minimum 6 characters',
    'agora.form.error.password.match': 'Passwords do not match',
    'agora.form.error.profession': 'Your profession is required',
    'agora.form.error.topic1': 'First topic is required',
    'agora.form.error.topic2': 'Second topic is required',
    'agora.form.error.topic3': 'Third topic is required',
    'agora.form.error.bio': 'Biography is required',
    'agora.form.error.bio.min': 'Biography must be at least 50 characters',
    'agora.form.error.location': 'Location is required',
    'agora.form.error.goals': 'Select at least one connection goal',

    // CONNECTION_GOALS options
    'agora.form.goal.networking.profesional': 'Professional Networking',
    'agora.form.goal.intercambio.de.conocimientos': 'Knowledge Exchange',
    'agora.form.goal.colaboraciones.creativas': 'Creative Collaborations',
    'agora.form.goal.mentoring.(dar.o.recibir)': 'Mentoring (Give or Receive)',
    'agora.form.goal.proyectos.conjuntos': 'Joint Projects',
    'agora.form.goal.amistad.intelectual': 'Intellectual Friendship',
    'agora.form.goal.desarrollo.de.negocios': 'Business Development',
    'agora.form.goal.aprendizaje.continuo': 'Continuous Learning',

    // LOOKING_FOR_OPTIONS
    'agora.form.looking.conexiones.profesionales': 'Professional Connections',
    'agora.form.looking.amistad.intelectual': 'Intellectual Friendship',
    'agora.form.looking.colaboraciones.creativas': 'Creative Collaborations',
    'agora.form.looking.intercambio.de.conocimientos': 'Knowledge Exchange',
    'agora.form.looking.mentoring': 'Mentoring',
    'agora.form.looking.proyectos.conjuntos': 'Joint Projects',
    'agora.form.looking.networking': 'Networking',
    'agora.form.looking.conversaciones.profundas': 'Deep Conversations',

    // Boulevard Registration Form
    'boulevard.form.title': 'Register My Business',
    'boulevard.form.subtitle': 'Create your commercial space in World Boulevard',
    'boulevard.form.cancel': 'Cancel',
    'boulevard.form.submit': '🛍️ Register on World Boulevard',
    'boulevard.form.business.name': 'Business Name *',
    'boulevard.form.business.name.placeholder': 'E.g.: Creative Kitchen María Santos',
    'boulevard.form.category': 'Category *',
    'boulevard.form.category.select': 'Select category',
    'boulevard.form.category.gastronomy': 'Gastronomy',
    'boulevard.form.category.technology': 'Technology',
    'boulevard.form.category.health': 'Health and Wellness',
    'boulevard.form.category.education': 'Education',
    'boulevard.form.category.art': 'Art and Culture',
    'boulevard.form.category.services': 'Professional Services',
    'boulevard.form.category.music': 'Music and Audio',
    'boulevard.form.category.design': 'Design and Creativity',
    'boulevard.form.category.retail': 'Retail and Commerce',
    'boulevard.form.category.other': 'Other',
    'boulevard.form.description': 'Business Description *',
    'boulevard.form.description.placeholder': 'Describe your business, what makes it unique, your experience and specialization...',
    'boulevard.form.products': 'Products and Services *',
    'boulevard.form.products.placeholder': 'List your main products or services (separated by commas)',
    'boulevard.form.email': 'Contact Email *',
    'boulevard.form.phone': 'Phone *',
    'boulevard.form.phone.placeholder': '+1 234 567 8900',
    'boulevard.form.website': 'Website (Optional)',
    'boulevard.form.website.placeholder': 'https://...',
    'boulevard.form.location': 'Location *',
    'boulevard.form.location.placeholder': 'City, Country',
    'boulevard.form.target': 'Who is your business targeted to?',
    'boulevard.form.target.placeholder': 'E.g.: Tech professionals, Families, Businesses, Artists...',
    'boulevard.form.experience': 'Years of Experience',
    'boulevard.form.experience.select': 'Select experience',
    'boulevard.form.experience.less1': 'Less than 1 year',
    'boulevard.form.experience.1to3': '1-3 years',
    'boulevard.form.experience.3to5': '3-5 years',
    'boulevard.form.experience.5to10': '5-10 years',
    'boulevard.form.experience.10to15': '10-15 years',
    'boulevard.form.experience.more15': 'More than 15 years',
    'boulevard.form.goals.title': 'What do you hope to achieve in World Boulevard?',
    'boulevard.form.goals.placeholder': 'E.g.: Connect with local clients, expand my professional network, showcase my work...',
    'boulevard.form.includes.title': 'Your space in World Boulevard includes:',
    'boulevard.form.includes.1': 'Featured business profile',
    'boulevard.form.includes.2': 'Expandable multimedia gallery',
    'boulevard.form.includes.3': 'Direct chat with customers',
    'boulevard.form.includes.4': 'Intelligent geolocation',
    'boulevard.form.includes.5': 'Interaction analytics',
    'boulevard.form.includes.6': 'Organic Commerce Certification',
    'boulevard.form.philosophy.title': 'World Boulevard Philosophy',
    'boulevard.form.philosophy.text': 'At World Boulevard, we believe in organic and authentic growth. Your business will grow through the quality of your products/services and the authenticity of your connections, not through manipulative algorithms.',
    'boulevard.form.success': 'Registration request sent! We will contact you soon to set up your space on World Boulevard. 🛍️✨',
    'boulevard.form.success.immediate': 'Profile created successfully!',
    'boulevard.form.success.visible': 'Your business is now visible on World Boulevard to all users.',
    'boulevard.form.submitting': 'Creating profile...',
    'boulevard.form.error': 'Error creating business. Please try again.',
    'boulevard.form.error.generic': 'An unexpected error occurred. Please try again.',
    'boulevard.form.scroll.help': '👇 Use slider to navigate',
    'boulevard.form.scroll.complete': '✅ Form complete',
    'boulevard.form.scroll.top': 'Go to top',
    'boulevard.form.scroll.bottom': 'Go to bottom',

    // WB Profile Editor
    'wb.edit.title': 'Edit Business Profile',
    'wb.edit.save': 'Save Changes',
    'wb.edit.saving': 'Saving...',
    'wb.edit.success': 'Profile updated successfully',
    'wb.edit.avatar.title': 'Logo / Profile Image',
    'wb.edit.gallery.title': 'Media Gallery',
    'wb.edit.gallery.description': 'Upload images of your products, services or facilities. You can mark one as featured for the carousel.',
    'wb.edit.button': 'Edit Profile',

    // Personal Profile Editor
    'profile.edit.title': 'Edit Personal Profile',
    'profile.edit.save': 'Save Changes',
    'profile.edit.saving': 'Saving...',
    'profile.edit.success': 'Profile updated successfully',
    'profile.edit.avatar.title': 'Profile Photo',
    'profile.edit.cover.title': 'Cover Image',
    'profile.edit.cover.description': 'Image that appears at the top of your profile',
    'profile.edit.gallery.title': 'Personal Gallery',
    'profile.edit.gallery.description': 'Upload photos of your moments, travels, projects or whatever you want to share',
    'profile.form.name': 'Full Name',
    'profile.form.profession': 'Profession',
    'profile.form.bio': 'Biography',
    'profile.form.location': 'Location',
    'profile.form.interests': 'Interests',
    'profile.form.cancel': 'Cancel',

    // Post Creator
    'post.create.title': 'Create Post',
    'post.create.type': 'Content type',
    'post.type.image': 'Image',
    'post.type.video': 'Video',
    'post.create.upload.image': 'Upload your image',
    'post.create.caption': 'Caption',
    'post.caption.placeholder': 'Write something about this post...',
    'post.create.tags': 'Tags',
    'post.tags.help': 'Comma separated. Help others find your content.',
    'post.visibility.public': 'Public post',
    'post.visibility.public.description': 'All Agora users will be able to see this post',
    'post.form.cancel': 'Cancel',
    'post.publish': 'Publish',
    'post.creating': 'Publishing...',
    'post.video.coming.soon': 'Short videos coming soon',
    'post.video.description': 'Soon you will be able to share videos up to 60 seconds',

    // Commercial Space Form
    'commercial.form.title': '💼 Commercial Spaces',
    'commercial.form.subtitle': 'Request your space on World Boulevard',
    'commercial.form.business.name': 'Business Name',
    'commercial.form.category': 'Category',
    'commercial.form.category.select': 'Select category',
    'commercial.form.category.gastronomy': 'Gastronomy',
    'commercial.form.category.technology': 'Technology',
    'commercial.form.category.health': 'Health and Wellness',
    'commercial.form.category.education': 'Education',
    'commercial.form.category.art': 'Art and Culture',
    'commercial.form.category.services': 'Professional Services',
    'commercial.form.category.retail': 'Retail and Commerce',
    'commercial.form.category.other': 'Other',
    'commercial.form.description': 'Business Description',
    'commercial.form.description.placeholder': 'Describe your business, products or services...',
    'commercial.form.email': 'Contact Email',
    'commercial.form.phone': 'Phone',
    'commercial.form.website': 'Website',
    'commercial.form.website.placeholder': 'https://...',
    'commercial.form.location': 'Location',
    'commercial.form.location.placeholder': 'City, Country',
    'commercial.form.includes.title': 'What does your commercial space include?',
    'commercial.form.includes.1': 'Featured profile on World Boulevard',
    'commercial.form.includes.2': 'Direct chat with potential customers',
    'commercial.form.includes.3': 'Geolocation for nearby customers',
    'commercial.form.includes.4': 'Interaction and visit analytics',
    'commercial.form.includes.5': 'Personalized support to optimize your presence',
    'commercial.form.submit': 'Request Commercial Space',
    'commercial.form.success': 'Request sent! We will contact you soon to set up your commercial space.',

    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'demo.mode': 'Demo Mode',
    'natural.intelligence': 'Natural Intelligence',
    'connect': 'Connect',
    'contact': 'Contact',
    'message': 'Message',
    'call': 'Call',
    'video.call': 'Video call',
    'voice.message': 'Voice message',
    'send': 'Send',
    'like': 'Like',
    'comment': 'Comment',
    'share': 'Share',
    'view.more': 'View more',
    'show.less': 'Show less',
    'read.more': 'Read more',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'finish': 'Finish',
    'continue': 'Continue',
    'skip': 'Skip',
    'done': 'Done',
    'yes': 'Yes',
    'no': 'No',
    'maybe': 'Maybe',
    'online': 'Online',
    'offline': 'Offline',
    'active': 'Active',
    'inactive': 'Inactive'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  // Detectar idioma del navegador al cargar
  useEffect(() => {
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('en')) {
      setLanguage('en');
    }
    
    // Cargar idioma guardado
    const savedLang = localStorage.getItem('humanbiblio-language') as Language;
    if (savedLang && (savedLang === 'es' || savedLang === 'en')) {
      setLanguage(savedLang);
    }
  }, []);

  // Guardar idioma seleccionado
  useEffect(() => {
    localStorage.setItem('humanbiblio-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}